version: '3.8'

services:
  app:
    build: .
    container_name: messagerie_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - vendor-data:/var/www/html/vendor
      - ./storage:/var/www/html/storage
    networks:
      - messagerie

  web:
    image: nginx:stable-alpine
    container_name: messagerie_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - messagerie

  db:
    image: mysql:8.0
    container_name: messagerie_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: messagerie
      MYSQL_ROOT_PASSWORD: ChangeMe123!
      MYSQL_USER: messagerie
      MYSQL_PASSWORD: ChangeMe123!
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - messagerie

networks:
  messagerie:
    driver: bridge

volumes:
  vendor-data: {}
  dbdata: {}